CREATE DATABASE T_InLock;

USE T_Gufos;

CREATE TABLE Usuarios(
	UsuarioId INT PRIMARY KEY IDENTITY NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(255) NOT NULL,
	PermissaoDoUsuario TEXT NOT NULL
);

CREATE TABLE Estudios(
	EstudioId INT PRIMARY KEY IDENTITY NOT NULL,
	NomeEstudio VARCHAR(255) NOT NULL,
	PaisOrigem VARCHAR(255) NOT NULL,
	DataCriacao DATE NOT NULL,
	UsuarioId INT FOREIGN KEY REFERENCES Usuarios(UsuarioId)
);

CREATE TABLE Jogos(
	JogoId INT PRIMARY KEY IDENTITY NOT NULL,
	NomeDoJogo VARCHAR(255) NOT NULL,
	Descricao VARCHAR(255) NOT NULL,
	DataLancamento DATE NOT NULL,
	Valor MONEY NOT NULL,
	EstudioId INT FOREIGN KEY REFERENCES Estudios(EstudioId)
);